version: '3.8'
services:
  gatepass:
    build: .
    ports:
      - "8080:8080"
    environment:
      - TWILIO_AUTH_TOKEN=$TWILIO_AUTH_TOKEN
      - TWILIO_ACCOUNT_SID=$TWILIO_ACCOUNT_SID
      - TWILIO_FROM_PHONE=$TWILIO_FROM_PHONE
      - ENV APP_NAME=$APP_NAME
      - ENV LANGUAGE=$LANGUAGE
    restart: unless-stopped
