// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Phone struct {
	Phone string `json:"phone"`
}

type Query struct {
}

type ResponseGetCode struct {
	Message string `json:"message"`
}

type ResponseVerifyCode struct {
	Authenticated bool    `json:"authenticated"`
	Message       *string `json:"message,omitempty"`
	Error         *string `json:"error,omitempty"`
	Phone         *string `json:"phone,omitempty"`
}

type Verification struct {
	Phone string `json:"phone"`
	Code  string `json:"code"`
}
